apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  labels:
    app.kubernetes.io/name: nexus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 20Gi
