apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    app.kubernetes.io/name: nexus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexus
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP